version: "3.3"

services:
  jupyter:
    image: jupyter/scipy-notebook
    environment:
      - JUPYTER_ENABLE_LAB="yes"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./requirements.txt:/home/jovyan/requirements.txt
      - ./configure_environment.sh:/usr/local/bin/before-notebook.d/configure_environment.sh
    ports:
      - 8888:8888
